---
title: "Tutorial de Uso do Pacote Bioma Stats"
author: "iuri"
date: "2023-05-13"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instalação

O _Bioma Stats_ é disponibilizado apenas como versão em desenvolvimento e deve ser instalado diretamente de repositório do GitHub (`iep-ferreira/biomastats`).    

```{r}
# para remover versões anteriores do pacote
#remove.packages("biomastats")
library(devtools)
#devtools::install_github("iep-ferreira/biomastats")
library(biomastats)
library(leaflet)
library(sf)
library(raster)
```

```{r results=FALSE}
(path_package <- system.file(package = "biomastats"))
figures_path <- "C:/Users/ferre/OneDrive/Área de Trabalho/pesquisa/Artigo-Biomastats-2023/figuras"
```
## Mar Egeu

```{r}
leaflet() %>%
  addProviderTiles(providers$OpenTopoMap ) %>% setView(lat =  -23.597323, lng =  -48.532440, zoom=12)
```

## Teste

```{r}
shp_file <- file.path(path_package, "shp/itapetininga.shp")
shp_brasil_file <- file.path(path_package,"shp/brasil_cortado.shp")
shp_ita <- sf::st_transform(sf::read_sf(shp_file), crs = 4326)
shp_brasil <- sf::st_transform(sf::read_sf(shp_brasil_file), crs = 4326)
library(mapview)
mapview(shp_ita) + mapview(shp_brasil)
```

# Teste recorte e visualização com os fragmentos 93 e 94

```{r}
recortes <- load_rasters(shape_path = shp_file,  start=1985, end=2021, data_from = "example")
```
```{r}
land_vis(recortes, year = 2013)
```




## Figure 1

```{r}
shp_file <- file.path(path_package, "shp/UFSCar.shp") 
ufscar_shp <- sf::read_sf(shp_file)
ufscar_shp <- sf::st_transform(ufscar_shp, crs = 4326)
# figura 1-A print
leaflet() %>%
  addProviderTiles(providers$OpenStreetMap) %>% addPolygons(data = ufscar_shp) %>% setView(lat = -23.602, lng = -48.524, zoom=14.4)
# figura 1-B print
cutout <- make_polygon(lat = -23.602, lon = -48.524, size = 2, shape = "hexagon")
leaflet() %>%
  addProviderTiles(providers$OpenMapSurfer.ContourLines ) %>% addPolygons(data = cutout$polygon) %>% setView(lat = -23.602, lng = -48.524, zoom=14.4)
```

## Figure 2 

```{r}
shp_brasil <- file.path(path_package,"shp/brasil_cortado.shp")
brasil <- sf::read_sf(shp_brasil)
brasil <- sf::st_transform(brasil, crs = 4326)
library(mapview)
mapview(brasil)
```

## Figure 3

```{r}
library(mapview)
cutout <- make_polygon(lat = -23.602, lon = -48.524, size = 1, shape = "hexagon")
```


```{r}
recortes <- load_rasters( shape_path =  shp_file,  start=1985, end=2021, data_from = "example")
mapview(cutout$polygon)
v <- sample(c(0,1), 1043, replace = TRUE)
plot(brasil$geometry, lwd = 0.3, col = v*2)
```

## Figure 4

```{r}
recortes <- load_rasters(shp_file, start=1985, end=2021, data_from = "example")
```


```{r}
#install.packages("flextable")
results <- get_area(recortes)
```

```{r}
library(DT)
library(kableExtra)
DT::datatable(results$aggregate_data)
df <- results$aggregate_data[1:10,] 
ch <- df %>%
  kbl(caption="") %>%
  kable_classic_2(full_width = F)
file.name <- file.path(figures_path,"mytab.docx")
library(flextable)
# Export to Word
ch <- as_flextable(ch)
save_as_docx(ch, path =  file.name)

```
```{r}
file.name <- file.path(figures_path,"time-serie.tiff")
tiff(file.name, res=600, width = 22, height = 12, units="cm")
results$time_series
dev.off()
```

```{r}
file.name <- file.path(figures_path,"cover-2020.tiff")
tiff(file.name, res=600, width = 18, height = 12, units="cm")
land_vis(recortes, year = 1990)
dev.off()
```


```{r}
file.name <- file.path(figures_path,"dist-2020.tiff")
tiff(file.name, res=600, width = 18, height = 12, units="cm")
land_dist(results, year = 2020, type = "barplot")
dev.off()
help(predict)
```

## Teste - área

```{r}
df <- results$aggregate_data
names(df)
sum(df[df$year==2020,]$area)
643*10000/10^6
```


  + Caso 2: Campus Lagoa do Sino e arredores


```{r}
region <- make_polygon(lat = -23.605, lon = -48.529, size = 1.5, shape = "hexagon")
```


```{r}
shp_path <- file.path(path_package, "shp/polygon.shp")
library(mapview)
mapview(sf::read_sf(shp_path))
```


```{r}
recortes <- load_rasters(shape_path = shp_path, start=1985, end=2021, data_from = "example")
```
```{r}
results <- get_area(recortes)
results$time_series
```

```{r}
land_vis(recortes, year = 1985)
```


```{r}
land_vis(recortes, year = 2000)
```

```{r}
land_vis(recortes, year = 2020)
```


```{r}
land_dist(results, year = 2020, type = "barplot")
```

